dev:
    image: coverit/golang-dev
    volumes:
      - .:/go/src/github.com/coverit/coverit
    working_dir: /go/src/github.com/coverit/coverit
    environment:
        - DEBUG=1
        - DB_NAME=test
    links:
        - mongodb:mongo
    ports:
        - "3000:3000"

mongodb:
    image: mongo:3.0.3
