#%RAML 0.8
---
title: Coverit
version: 0.0.1
baseUri: http://api.coverit.io/
mediaType:  application/json
securedBy: [oauth_2_0]

documentation:
    - title: Objects
      content: !include README.md

securitySchemes:
    - oauth_2_0: !include http://raml.link/securitySchemes/oauth_2_0.yml

/upload:
    displayName: Upload coverage report
    post:
        description: |
            Upload coverage report
        body:
            application/x-www-form-urlencoded:
                formParameters:
                    token:
                        description: Repo Token
                        type: string
                        required: true
                        example: AFNetworking/AFNetworking
                    report:
                        description: Report file, it's type should carried in `Content-Type`
                        type: file
                    git_commit:
                        description: Git commit sha in 10 chars
                        type: string
                        required: true
                        example: 09b26bf784
                    git_branch:
                        description: Git branch
                        type: string
                        required: true
                        example: master

/users:
    displayName: User
    post:
        description: |
            Create a user
        body:
            schema: |
                name: string
                password: string
                email: email
        responses:
            201:
                body:
                    schema: |
                        _id: string
    /{user_id}:
        uriParameters:
            user_id:
                description: User ID
                type: string
                example: '4ed2b809d7446b9a0e000014'
        get:
            description: Get user info
            responses:
                200:
                    body:
                        schema: |
                            _id: string
                            name: string
                            source: string

/projects:
    displayName: Project
    post:
        description: |
            Create a project
        body:
            schema: |
                name: string
                repo_url: url
                repo_sshkey: string
        responses:
            201:
                body:
                    schema: |
                        _id: string
                        name: string
                        repo_url: url
    get:
        description: |
            List projects
        queryParameters:
            user_id:
                description: User id
                example: coverit
        responses:
            200:
                body:
                    schema: |
                        [
                            _id: string
                            name: string
                            repo_url: url
                        ]


/builds:
    displayName: Build
    get:
        description: |
            List builds
        queryParameters:
            project:
                description: Project name
                example: coverit/coverit
            branch:
                description: Project branch
                example: master
        responses:
            200:
                body:
                    schema: |
                        [
                            _id: string
                            git:
                                branch: string
                                commit: string
                                date: time
                                commiter: string
                                type: string
                            platform: string
                            coverage: int
                            reports: [string]
                        ]
    /{build_id}:
        uriParameters:
            build_id:
                description: Build ID
                type: string
                example: '4ed2b809d7446b9a0e000014'
        get:
            description: |
                Get build info
            responses:
                200:
                    body:
                        schema: |
                            _id: string
                            git:
                                branch: string
                                commit: string
                                date: time
                                commiter: string
                                type: string
                            platform: string
                            coverage: int
                            reports: [string]

/reports:
    displayName: Report
    /{report_id}:
        uriParameters:
            report_id:
                description: Report ID
                type: string
                example: '4ed2b809d7446b9a0e000014'
        get:
            description: |
                Get report
            responses:
                200:
                    body:
                        schema: |
                            _id: string
                            user: string
                            project: string
                            build:
                                git:
                                    commit: string
                                    branch: string
                                    date: time
                            files: [
                                name: string
                                coverage: int
                                lines: int
                                hit: int
                            ]

        /{file_name}:
            uriParameters:
                file_name:
                    description: File name
                    type: string
                    example: 'coverit/main.go'
            get:
                description: |
                    Get source level coverage info
                responses:
                    200:
                        body:
                            schema: |
                                user: string
                                project: string
                                file: string
                                source: string
                                line_coverage: [
                                    line_no: int
                                    hit: int
                                ]
                                coverage: int
                                lines: int

/services:
    displayName: Service
    /github:
        description: Github service
        /create_user:
            description: Sign up thru Github
        /projects:
            get:
                description: List current user's Github projects
                responses:
                    200:
