#%RAML 0.8
---
title: Coverit
version: 0.0.1
baseUri: http://api.coverit.io/
mediaType:  application/json
securedBy: [oauth_2_0]

documentation:
    - title: Objects
      content: !include README.md

securitySchemes:
    - oauth_2_0: !include http://raml.link/securitySchemes/oauth_2_0.yml

/builds:
    displayName: Build
    post:
        description: |
            Create a new build
        body:
            application/x-www-form-urlencoded:
                formParameters:
                    project_name:
                        description: Project name
                        type: string
                        required: true
                        example: /AFNetworking
                    gcno:
                        description: gcno files archive
                        type: file
                        required: true
                    commit_sha:
                        description: Git commit SHA
                        type: string
                        required: true
                        example: 0db872a7825b5860109710911cbe9e23133f39df
                    branch:
                        description: Git branch
                        type: string
                        required: true
                        example: master
