#%RAML 0.8
---
title: Coverit
version: 0.0.1
baseUri: http://api.coverit.io/
mediaType:  application/json
securedBy: [oauth_2_0]

documentation:
    - title: Objects
      content: !include README.md

securitySchemes:
    - oauth_2_0: !include http://raml.link/securitySchemes/oauth_2_0.yml

/builds:
    displayName: Build
    post:
        description: |
            Create a new build
        body:
            application/x-www-form-urlencoded:
                formParameters:
                    project_name:
                        description: Project name
                        type: string
                        required: true
                        example: AFNetworking/AFNetworking
                    gcno:
                        description: gcno files archive
                        type: file
                        required: true
                    git:
                        description: A hash of Git data that can be used to display more information to users.
                        type: string
                        example: '
                            "git": {
                              "head": {
                                "id": "b31f08d07ae564b08237e5a336e478b24ccc4a65",
                                "author_name": "Nick Merwin",
                                "author_email": "...",
                                "committer_name": "Nick Merwin",
                                "committer_email": "...",
                                "message": "version bump"
                              },
                              "branch": "master",
                              "remotes": [
                                {
                                  "name": "origin",
                                  "url": "git@github.com:lemurheavy/coveralls-ruby.git"
                                }
                              ]
                            }'

/reports:
    displayName: Report
    post:
        description: |
            Create a new report
        body:
            application/x-www-form-urlencoded:
                formParameters:
                    project_name:
                        description: Project name
                        type: string
                        required: true
                        example: AFNetworking/AFNetworking
                    lcov:
                        description: lcov files archive
                        type: file
                        required: true
                    git:
                        description: A hash of Git data that can be used to display more information to users.
                        type: string
                        example: '
                            "git": {
                              "head": {
                                "id": "b31f08d07ae564b08237e5a336e478b24ccc4a65",
                                "author_name": "Nick Merwin",
                                "author_email": "...",
                                "committer_name": "Nick Merwin",
                                "committer_email": "...",
                                "message": "version bump"
                              },
                              "branch": "master",
                              "remotes": [
                                {
                                  "name": "origin",
                                  "url": "git@github.com:lemurheavy/coveralls-ruby.git"
                                }
                              ]
                            }'
